user_name: "ZJUshine"
repo_name: "zjushine-arxiv-daily"
show_authors: True
show_links: True
max_results: 10

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './zjushine-arxiv-daily.json'
json_gitpage_path: './zjushine-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './index.md'

# keywords to search
keywords:
    "LLM Security": 
        filters: ["LLM Security"]
    "LLM Application":
        filters: ["LLM Application"]

