title: ZJUshine Arxiv Daily
description: Automatically Update Arixiv Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/ZJUshine/zjushine-arxiv-daily
  another_url: https://github.com/ZJUshine/zjushine-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter: None
  github: ZJUshine

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag